services:
  action-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    env_file:
      - .env

  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    env_file:
      - .env
    environment:
      DRY_RUN: "1"
